name = "Triple H"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Customization of the Kross Hugo Template"
homepage = "https://github.com/hannahhenderson/triple-h-hugo-template"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'triple-h', 'tripleh', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.54"

[author]
  name = "Hannah Henderson"
  homepage = "https://www.hannah-henderson.com/"